-- Fix business_units id column to auto-increment like other lookup tables.
-- Previously used explicit IDs for seeds, but INSERT now fails without a provided id.
-- This migration adds identity and restarts the sequence after existing max ID.

DO $$
DECLARE
    max_id INTEGER;
BEGIN
    -- Check if column already has an identity
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'business_units'
        AND column_name = 'id'
        AND is_identity = 'YES'
    ) THEN
        -- Remove any old serial/default expression before adding a PostgreSQL identity.
        ALTER TABLE public.business_units ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE public.business_units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    -- Get the maximum existing ID
    SELECT COALESCE(MAX(id), 0) + 1 INTO max_id FROM public.business_units;

    -- Restart the identity through the column, avoiding sequence-name assumptions.
    EXECUTE format('ALTER TABLE public.business_units ALTER COLUMN id RESTART WITH %s', max_id);
END $$;
